# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='platform_id',
            field=models.CharField(max_length=255),
        ),
    ]
