# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_name',
            field=models.CharField(default='client', max_length=255),
            preserve_default=False,
        ),
    ]
