# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
